"""Public error codes, preserving the historical retrieval contracts."""

LEGACY_ERROR_CODES = frozenset({
    "SYSTEM_ERROR", "MISSING_PROJECT_SCOPE", "AMBIGUOUS_PROJECT_REF",
    "INVALID_PROJECT_REF", "INDEX_UNAVAILABLE", "MISSING_KNOWLEDGE_SCOPE",
    "AMBIGUOUS_DOMAIN_REF", "INVALID_INPUT", "INVALID_EVIDENCE_ID",
})

MEMORY_ERROR_CODES = frozenset({
    "MISSING_KNOWLEDGE_SCOPE", "AMBIGUOUS_DOMAIN_REF",
    "MEMORY_EVIDENCE_ANCHOR_REQUIRED", "MEMORY_EVIDENCE_SCOPE_MISMATCH",
    "MEMORY_INFERENCE_META_INCOMPLETE", "MEMORY_PROVENANCE_INVALID",
    "MEMORY_KIND_INVALID", "MEMORY_SUPERSEDE_TARGET_INVALID",
    "MEMORY_QUOTA_EXCEEDED", "MEMORY_WRITE_UNAVAILABLE",
    "MEMORY_IDS_QUERY_CONFLICT", "MEMORY_ROLLBACK_FORBIDDEN",
    "MEMORY_TIMEOUT", "MEMORY_CONTENT_CONFLICT", "SYSTEM_ERROR",
})

ERROR_CODES = LEGACY_ERROR_CODES | MEMORY_ERROR_CODES
