"""014 T010: the untriggered ``search_knowledge`` response is byte-frozen.

FR-001/FR-002/SC-001: as long as neither ``session_id`` nor ``memory_context`` is
explicitly supplied, the response must be byte-identical to the 012 behaviour —
same key set, same key order, same ``structuredContent``, same pretty text mirror
and the same wire literal. Explicit ``null`` is equivalent to omission: it is not
a signal, so it must neither attach memories nor raise.

The golden literals come from T002's fixtures, which were generated by running the
real FastMCP registration + result conversion, not hand-written.
"""

from __future__ import annotations

import json
from contextlib import asynccontextmanager
from pathlib import Path

import pytest
from mcp.types import CallToolResult, TextContent

import rag_mcp.mcp.search_knowledge as search_module
from rag_mcp.mcp import create_mcp_server
from rag_mcp.providers.local_cpu import LocalCPUEmbeddingProvider
from tests.contract import schema_registry_014 as reg

FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "014"
SEARCH_GOLDEN = json.loads((FIXTURE_DIR / "legacy_search_knowledge.golden.json").read_text(encoding="utf-8"))

REQUEST_ID = "00000000-0000-4000-8000-000000000000"
_EVIDENCE = [{
    "evidence_id": "e-1", "content_excerpt": "excerpt", "source_version": 1,
    "source_position": "doc.md#L1", "knowledge_scope_id": "1",
    "knowledge_scope_type": "project", "relevance_score": 0.9,
}]

#: The exact bodies the T002 golden was generated from. Keeping them byte-equal to
#: the generator (including the request id) is what makes the mirror/wire
#: comparison meaningful.
BRANCH_BODIES: dict[str, dict] = {
    "complete": {"completion_status": "complete", "evidence": _EVIDENCE, "request_id": REQUEST_ID},
    "partial": {"completion_status": "partial", "evidence": _EVIDENCE, "request_id": REQUEST_ID,
                "gaps": [{"description": "insufficient evidence",
                          "suggested_action": "broaden the query"}]},
    "no_evidence": {"completion_status": "no_evidence", "evidence": [], "request_id": REQUEST_ID},
    "failed": {"completion_status": "failed", "evidence": [],
               "error": {"code": "SYSTEM_ERROR", "message": "boom"}, "request_id": REQUEST_ID},
}


class _OfflineQdrant:
    _client = None


class _FakeSession:
    async def commit(self):
        return None

    async def rollback(self):
        return None


@asynccontextmanager
async def _fake_session_factory():
    yield _FakeSession()


def _install_fake_retrieval(monkeypatch, body: dict):
    """Stub only RetrievalService.search; keep the rest of the tool path real."""

    class _FakeRetrievalService:
        def __init__(self, **_kwargs):
            pass

        async def search(self, **_kwargs):
            return body

    monkeypatch.setattr(search_module, "RetrievalService", _FakeRetrievalService)


def _server():
    return create_mcp_server(
        session_factory=_fake_session_factory,
        qdrant_store=_OfflineQdrant(),
        embedding_provider=LocalCPUEmbeddingProvider(),
        mode="writer",
    )


async def _call_tool(arguments: dict):
    return await _server().call_tool("search_knowledge", arguments)


async def _call_core(monkeypatch, body, **signals):
    _install_fake_retrieval(monkeypatch, body)
    return await search_module.search_knowledge_core(
        query="q",
        project_scope=["p"],
        top_k=5,
        task_context=None,
        session_factory=_fake_session_factory,
        qdrant_store=_OfflineQdrant(),
        embedding_provider=LocalCPUEmbeddingProvider(),
        **signals,
    )


@pytest.mark.parametrize("branch", sorted(SEARCH_GOLDEN["branches"]))
async def test_untriggered_core_key_order_matches_golden(monkeypatch, branch):
    golden = SEARCH_GOLDEN["branches"][branch]
    result = await _call_core(monkeypatch, BRANCH_BODIES[branch])
    assert list(result) == golden["body_keys"]


async def test_untriggered_result_is_the_same_object_untouched(monkeypatch):
    body = {"completion_status": "complete", "evidence": [], "request_id": "r"}
    result = await _call_core(monkeypatch, body)
    assert result is body
    assert list(result) == ["completion_status", "evidence", "request_id"]


@pytest.mark.parametrize("branch", sorted(SEARCH_GOLDEN["branches"]))
async def test_untriggered_mirror_and_wire_match_golden(monkeypatch, branch):
    golden = SEARCH_GOLDEN["branches"][branch]
    _install_fake_retrieval(monkeypatch, BRANCH_BODIES[branch])
    content, structured = await _call_tool(SEARCH_GOLDEN["arguments"])
    assert list(structured) == golden["body_keys"]
    assert content[0].text == golden["pretty_mirror"]
    wire = CallToolResult(structuredContent=structured, content=list(content), isError=False) \
        .model_dump_json(by_alias=True, exclude_none=True)
    assert wire == golden["wire"]


async def test_explicit_null_signals_are_equivalent_to_omission(monkeypatch):
    _install_fake_retrieval(monkeypatch, BRANCH_BODIES["complete"])
    content, structured = await _call_tool({
        "query": "q", "project_scope": ["p"], "session_id": None, "memory_context": None,
    })
    golden = SEARCH_GOLDEN["branches"]["complete"]
    assert list(structured) == golden["body_keys"]
    assert content[0].text == golden["pretty_mirror"]


async def test_agentic_switch_on_keeps_the_untriggered_response_byte_identical(monkeypatch):
    """Approved decision 4: the agentic path attaches nothing and must not move bytes."""
    from rag_mcp.orchestration.entry import AgenticPathUnavailable

    _install_fake_retrieval(monkeypatch, BRANCH_BODIES["complete"])

    async def _unavailable(**_kwargs):
        raise AgenticPathUnavailable("no provider configured")

    monkeypatch.setattr(search_module, "_run_agentic_search", _unavailable)
    monkeypatch.setenv("AGENTIC_RETRIEVAL_ENABLED", "true")

    content, structured = await _call_tool(SEARCH_GOLDEN["arguments"])
    golden = SEARCH_GOLDEN["branches"]["complete"]
    assert list(structured) == golden["body_keys"]
    assert content[0].text == golden["pretty_mirror"]


async def test_agentic_success_with_explicit_signals_attaches_nothing(monkeypatch):
    """T090 / approved decision 4: a *successful* agentic run returns its own dict
    and grows no 014 fields, even when the caller supplied explicit signals."""
    agentic_body = {"completion_status": "complete", "evidence": [{"evidence_id": "e-agentic"}],
                    "request_id": "agentic-r"}

    async def _agentic(**_kwargs):
        return agentic_body

    _install_fake_retrieval(monkeypatch, BRANCH_BODIES["complete"])
    monkeypatch.setattr(search_module, "_run_agentic_search", _agentic)
    monkeypatch.setenv("AGENTIC_RETRIEVAL_ENABLED", "true")

    _content, structured = await _call_tool({
        "query": "q", "project_scope": ["p"],
        "session_id": "11111111-1111-1111-1111-111111111111", "memory_context": "ctx",
    })
    assert structured == agentic_body
    assert list(structured) == ["completion_status", "evidence", "request_id"]


def test_memory_context_empty_is_a_parameter_error_not_a_silent_no_op():
    tool = _server()._tool_manager.get_tool("search_knowledge")
    arguments = {"query": "q", "project_scope": ["p"], "memory_context": ""}
    with pytest.raises(Exception) as error:  # noqa: PT011 - the exact type is mcp's
        tool.fn_metadata.arg_model.model_validate(arguments)
    assert "memory_context" in str(error.value)


@pytest.mark.parametrize("bad_session", ["not-a-uuid", "12345", ""])
def test_invalid_session_id_is_a_parameter_error_not_a_silent_no_op(bad_session):
    tool = _server()._tool_manager.get_tool("search_knowledge")
    arguments = {"query": "q", "project_scope": ["p"], "session_id": bad_session}
    with pytest.raises(Exception) as error:  # noqa: PT011 - the exact type is mcp's
        tool.fn_metadata.arg_model.model_validate(arguments)
    assert "session_id" in str(error.value)


@pytest.mark.parametrize("signals", [{"session_id": "not-a-uuid"}, {"memory_context": ""}])
async def test_core_rejects_invalid_signals_instead_of_silently_skipping(monkeypatch, signals):
    _install_fake_retrieval(monkeypatch, {"completion_status": "complete", "evidence": [], "request_id": "r"})
    with pytest.raises(ValueError):
        await _call_core(
            monkeypatch, {"completion_status": "complete", "evidence": [], "request_id": "r"}, **signals
        )


def test_legacy_mirror_is_pretty_printed_and_the_wire_carries_it():
    """Guard the two serializers stay distinct: pretty mirror, compact memory tools."""
    golden = SEARCH_GOLDEN["branches"]["complete"]
    assert "\n  " in golden["pretty_mirror"], "search_knowledge mirrors at indent=2"
    wire = json.loads(golden["wire"])
    assert wire["structuredContent"] == json.loads(golden["pretty_mirror"])
    assert wire["isError"] is False
    assert wire["content"][0]["type"] == "text"
    assert wire["content"][0]["text"] == golden["pretty_mirror"]
    assert isinstance(TextContent(type="text", text="x"), TextContent)


# --- T021: the 014 branch order is frozen in three places ---------------------

FIXTURE_014_ORDER = ["completion_status", "evidence", "related_memories", "memory_notice",
                     "counts", "gaps", "error", "request_id"]


def _documented_014_order() -> list[str]:
    """Read the frozen 014 order out of field-order-contract.md §2."""
    doc = Path(search_module.__file__).resolve().parents[4] / "specs" / "014-memory-aware-retrieval" \
        / "contracts" / "field-order-contract.md"
    for line in doc.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("completion_status, evidence, related_memories"):
            return [part.strip() for part in stripped.split(",")]
    raise AssertionError("field-order-contract.md §2 no longer declares the 014 order")


def test_runtime_order_equals_the_schema_declaration_order():
    declared = list(reg.load("mcp-search-output.schema.json")["properties"])
    assert search_module.ATTACHMENT_FIELD_ORDER == tuple(declared[:8])
    assert FIXTURE_014_ORDER == list(declared[:8])


def test_documented_order_equals_the_runtime_and_schema_order():
    """The three places must agree: contract doc, schema declaration, assertion."""
    assert _documented_014_order() == FIXTURE_014_ORDER
    assert tuple(_documented_014_order()) == search_module.ATTACHMENT_FIELD_ORDER


@pytest.mark.parametrize("status", ["complete", "partial", "no_evidence"])
def test_014_branch_key_order_is_exactly_the_contract_table(status):
    """The emitted key list is the frozen table minus the keys that must be absent."""
    primary = {"completion_status": status, "evidence": [], "request_id": "r"}
    if status == "partial":
        primary["gaps"] = [{"description": "gap", "suggested_action": "act"}]
    merged = search_module.merge_attachment_response(
        primary, {"items": [], "counts": {}, "failed_paths": []}
    )
    expected = [key for key in FIXTURE_014_ORDER if key in merged]
    assert list(merged) == expected
    assert list(merged)[:5] == ["completion_status", "evidence", "related_memories",
                                "memory_notice", "counts"]
    if status == "partial":
        assert list(merged)[-2:] == ["gaps", "request_id"], "gaps precedes request_id"
    else:
        assert list(merged)[-1] == "request_id"
        assert "gaps" not in merged and "error" not in merged


def test_014_branch_keeps_related_memories_next_to_evidence():
    primary = {"completion_status": "complete", "evidence": [{"evidence_id": "e"}], "request_id": "r"}
    merged = search_module.merge_attachment_response(primary, {"items": [{"memory_id": 1}],
                                                              "counts": {}, "failed_paths": []})
    keys = list(merged)
    assert keys.index("related_memories") == keys.index("evidence") + 1


def test_failed_branch_carries_no_new_fields():
    primary = {"completion_status": "failed", "evidence": [],
               "error": {"code": "SYSTEM_ERROR", "message": "boom"}, "request_id": "r"}
    # merge is only reachable for a non-failed primary, so model the runtime rule
    # explicitly: the failed primary is returned as-is.
    assert list(primary) == ["completion_status", "evidence", "error", "request_id"]


def test_014_branch_omits_keys_instead_of_setting_them_to_none():
    primary = {"completion_status": "complete", "evidence": [], "request_id": "r"}
    merged = search_module.merge_attachment_response(primary, {"items": [], "counts": {},
                                                              "failed_paths": []})
    for key in ("gaps", "error"):
        assert key not in merged, f"{key} must be omitted, not set to None"
    assert merged["related_memories"] == []
    assert merged["memory_notice"] == {"notice": search_module.MEMORY_NOTICE_TEXT, "untrusted": True}
    assert list(merged["counts"]) == ["returned", "candidates", "truncated_by_budget",
                                      "dropped_delivered", "filtered_inactive", "characters"]


def test_014_branch_never_drops_or_reorders_evidence():
    evidence = [{"evidence_id": "e-1"}, {"evidence_id": "e-2"}]
    primary = {"completion_status": "complete", "evidence": evidence, "request_id": "r"}
    merged = search_module.merge_attachment_response(primary, {"items": [{"memory_id": 9}],
                                                              "counts": {}, "failed_paths": []})
    assert merged["evidence"] is evidence


def test_counts_vocabulary_and_order_match_the_012_recall_counts():
    """FR-014/§4: one parser must handle both recall_memory and search_knowledge counts."""
    from rag_mcp.services.memory_reader import MemoryReader  # noqa: F401 - documents the source

    declared = list(reg.load("mcp-search-output.schema.json")["properties"]["counts"]["properties"])
    assert declared == ["returned", "candidates", "truncated_by_budget", "dropped_delivered",
                        "filtered_inactive", "characters"]


async def test_end_to_end_014_branch_order_through_the_real_tool(monkeypatch):
    _install_fake_retrieval(monkeypatch, BRANCH_BODIES["complete"])
    monkeypatch.setenv("MEMORY_AWARE_RETRIEVAL_ENABLED", "true")

    import rag_mcp.mcp.search_knowledge as module

    class _FakeMemoryService:
        def __init__(self, *_args, **_kwargs):
            pass

        async def attach(self, **_kwargs):
            return {"items": [], "counts": {"returned": 0, "candidates": 0,
                                            "truncated_by_budget": 0, "dropped_delivered": 0,
                                            "filtered_inactive": 0, "characters": 0},
                    "failed_paths": ["below_min_score"]}

    monkeypatch.setattr(module, "MemoryService", _FakeMemoryService)
    content, structured = await _call_tool({
        "query": "q", "project_scope": ["p"], "memory_context": "some context",
    })
    assert list(structured) == [key for key in FIXTURE_014_ORDER if key in structured]
    assert list(structured)[:5] == ["completion_status", "evidence", "related_memories",
                                    "memory_notice", "counts"]
    # The mirror keeps the same order in the pretty text.
    assert content[0].text.index('"related_memories"') > content[0].text.index('"evidence"')


async def test_end_to_end_failed_primary_has_no_new_fields(monkeypatch):
    _install_fake_retrieval(monkeypatch, BRANCH_BODIES["failed"])
    monkeypatch.setenv("MEMORY_AWARE_RETRIEVAL_ENABLED", "true")

    import rag_mcp.mcp.search_knowledge as module

    class _FakeMemoryService:
        def __init__(self, *_args, **_kwargs):
            pass

        async def attach(self, **_kwargs):
            raise AssertionError("a failed primary must not be attached")

    monkeypatch.setattr(module, "MemoryService", _FakeMemoryService)
    _, structured = await _call_tool({"query": "q", "project_scope": ["p"], "session_id": REQUEST_ID})
    assert list(structured) == ["completion_status", "evidence", "error", "request_id"]


def test_merge_sanitizes_related_memories_and_rejects_evidence_items():
    """T088: the runtime merge point is the last line of defence against mixing."""
    primary = {"completion_status": "complete", "evidence": [{"evidence_id": "e-1"}], "request_id": "r"}
    merged = search_module.merge_attachment_response(primary, {
        "items": [
            {"memory_id": 1, "source_position": "p",
             "match": {"dense_similarity": 0.9, "relevance_score": 0.5}},
            {"evidence_id": "e-2"},   # an evidence item must never be merged
            "not-a-mapping",
        ],
        "counts": {}, "failed_paths": [],
    })
    assert [item["memory_id"] for item in merged["related_memories"]] == [1]
    assert "source_position" not in merged["related_memories"][0]
    assert "relevance_score" not in merged["related_memories"][0]["match"]
    assert merged["evidence"] == [{"evidence_id": "e-1"}]
