"""014 T010: the untriggered ``search_knowledge`` response is byte-frozen.

FR-001/FR-002/SC-001: as long as neither ``session_id`` nor ``memory_context`` is
explicitly supplied, the response must be byte-identical to the 012 behaviour —
same key set, same key order, same ``structuredContent``, same pretty text mirror
and the same wire literal. Explicit ``null`` is equivalent to omission: it is not
a signal, so it must neither attach memories nor raise.

The golden literals come from T002's fixtures, which were generated by running the
real FastMCP registration + result conversion, not hand-written.
"""

from __future__ import annotations

import json
from contextlib import asynccontextmanager
from pathlib import Path

import pytest
from mcp.types import CallToolResult, TextContent

import rag_mcp.mcp.search_knowledge as search_module
from rag_mcp.mcp import create_mcp_server
from rag_mcp.providers.local_cpu import LocalCPUEmbeddingProvider

FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "014"
SEARCH_GOLDEN = json.loads((FIXTURE_DIR / "legacy_search_knowledge.golden.json").read_text(encoding="utf-8"))

REQUEST_ID = "00000000-0000-4000-8000-000000000000"
_EVIDENCE = [{
    "evidence_id": "e-1", "content_excerpt": "excerpt", "source_version": 1,
    "source_position": "doc.md#L1", "knowledge_scope_id": "1",
    "knowledge_scope_type": "project", "relevance_score": 0.9,
}]

#: The exact bodies the T002 golden was generated from. Keeping them byte-equal to
#: the generator (including the request id) is what makes the mirror/wire
#: comparison meaningful.
BRANCH_BODIES: dict[str, dict] = {
    "complete": {"completion_status": "complete", "evidence": _EVIDENCE, "request_id": REQUEST_ID},
    "partial": {"completion_status": "partial", "evidence": _EVIDENCE, "request_id": REQUEST_ID,
                "gaps": [{"description": "insufficient evidence",
                          "suggested_action": "broaden the query"}]},
    "no_evidence": {"completion_status": "no_evidence", "evidence": [], "request_id": REQUEST_ID},
    "failed": {"completion_status": "failed", "evidence": [],
               "error": {"code": "SYSTEM_ERROR", "message": "boom"}, "request_id": REQUEST_ID},
}


class _OfflineQdrant:
    _client = None


class _FakeSession:
    async def commit(self):
        return None

    async def rollback(self):
        return None


@asynccontextmanager
async def _fake_session_factory():
    yield _FakeSession()


def _install_fake_retrieval(monkeypatch, body: dict):
    """Stub only RetrievalService.search; keep the rest of the tool path real."""

    class _FakeRetrievalService:
        def __init__(self, **_kwargs):
            pass

        async def search(self, **_kwargs):
            return body

    monkeypatch.setattr(search_module, "RetrievalService", _FakeRetrievalService)


def _server():
    return create_mcp_server(
        session_factory=_fake_session_factory,
        qdrant_store=_OfflineQdrant(),
        embedding_provider=LocalCPUEmbeddingProvider(),
        mode="writer",
    )


async def _call_tool(arguments: dict):
    return await _server().call_tool("search_knowledge", arguments)


async def _call_core(monkeypatch, body, **signals):
    _install_fake_retrieval(monkeypatch, body)
    return await search_module.search_knowledge_core(
        query="q",
        project_scope=["p"],
        top_k=5,
        task_context=None,
        session_factory=_fake_session_factory,
        qdrant_store=_OfflineQdrant(),
        embedding_provider=LocalCPUEmbeddingProvider(),
        **signals,
    )


@pytest.mark.parametrize("branch", sorted(SEARCH_GOLDEN["branches"]))
async def test_untriggered_core_key_order_matches_golden(monkeypatch, branch):
    golden = SEARCH_GOLDEN["branches"][branch]
    result = await _call_core(monkeypatch, BRANCH_BODIES[branch])
    assert list(result) == golden["body_keys"]


async def test_untriggered_result_is_the_same_object_untouched(monkeypatch):
    body = {"completion_status": "complete", "evidence": [], "request_id": "r"}
    result = await _call_core(monkeypatch, body)
    assert result is body
    assert list(result) == ["completion_status", "evidence", "request_id"]


@pytest.mark.parametrize("branch", sorted(SEARCH_GOLDEN["branches"]))
async def test_untriggered_mirror_and_wire_match_golden(monkeypatch, branch):
    golden = SEARCH_GOLDEN["branches"][branch]
    _install_fake_retrieval(monkeypatch, BRANCH_BODIES[branch])
    content, structured = await _call_tool(SEARCH_GOLDEN["arguments"])
    assert list(structured) == golden["body_keys"]
    assert content[0].text == golden["pretty_mirror"]
    wire = CallToolResult(structuredContent=structured, content=list(content), isError=False) \
        .model_dump_json(by_alias=True, exclude_none=True)
    assert wire == golden["wire"]


async def test_explicit_null_signals_are_equivalent_to_omission(monkeypatch):
    _install_fake_retrieval(monkeypatch, BRANCH_BODIES["complete"])
    content, structured = await _call_tool({
        "query": "q", "project_scope": ["p"], "session_id": None, "memory_context": None,
    })
    golden = SEARCH_GOLDEN["branches"]["complete"]
    assert list(structured) == golden["body_keys"]
    assert content[0].text == golden["pretty_mirror"]


async def test_agentic_switch_on_keeps_the_untriggered_response_byte_identical(monkeypatch):
    """Approved decision 4: the agentic path attaches nothing and must not move bytes."""
    from rag_mcp.orchestration.entry import AgenticPathUnavailable

    _install_fake_retrieval(monkeypatch, BRANCH_BODIES["complete"])

    async def _unavailable(**_kwargs):
        raise AgenticPathUnavailable("no provider configured")

    monkeypatch.setattr(search_module, "_run_agentic_search", _unavailable)
    monkeypatch.setenv("AGENTIC_RETRIEVAL_ENABLED", "true")

    content, structured = await _call_tool(SEARCH_GOLDEN["arguments"])
    golden = SEARCH_GOLDEN["branches"]["complete"]
    assert list(structured) == golden["body_keys"]
    assert content[0].text == golden["pretty_mirror"]


def test_memory_context_empty_is_a_parameter_error_not_a_silent_no_op():
    tool = _server()._tool_manager.get_tool("search_knowledge")
    arguments = {"query": "q", "project_scope": ["p"], "memory_context": ""}
    with pytest.raises(Exception) as error:  # noqa: PT011 - the exact type is mcp's
        tool.fn_metadata.arg_model.model_validate(arguments)
    assert "memory_context" in str(error.value)


@pytest.mark.parametrize("bad_session", ["not-a-uuid", "12345", ""])
def test_invalid_session_id_is_a_parameter_error_not_a_silent_no_op(bad_session):
    tool = _server()._tool_manager.get_tool("search_knowledge")
    arguments = {"query": "q", "project_scope": ["p"], "session_id": bad_session}
    with pytest.raises(Exception) as error:  # noqa: PT011 - the exact type is mcp's
        tool.fn_metadata.arg_model.model_validate(arguments)
    assert "session_id" in str(error.value)


@pytest.mark.parametrize("signals", [{"session_id": "not-a-uuid"}, {"memory_context": ""}])
async def test_core_rejects_invalid_signals_instead_of_silently_skipping(monkeypatch, signals):
    _install_fake_retrieval(monkeypatch, {"completion_status": "complete", "evidence": [], "request_id": "r"})
    with pytest.raises(ValueError):
        await _call_core(
            monkeypatch, {"completion_status": "complete", "evidence": [], "request_id": "r"}, **signals
        )


def test_legacy_mirror_is_pretty_printed_and_the_wire_carries_it():
    """Guard the two serializers stay distinct: pretty mirror, compact memory tools."""
    golden = SEARCH_GOLDEN["branches"]["complete"]
    assert "\n  " in golden["pretty_mirror"], "search_knowledge mirrors at indent=2"
    wire = json.loads(golden["wire"])
    assert wire["structuredContent"] == json.loads(golden["pretty_mirror"])
    assert wire["isError"] is False
    assert wire["content"][0]["type"] == "text"
    assert wire["content"][0]["text"] == golden["pretty_mirror"]
    assert isinstance(TextContent(type="text", text="x"), TextContent)
